//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asis_language
    {
        public int IDAsisLanguage { get; set; }
        public string NameNL { get; set; }
        public string NameEN { get; set; }
        public string Code { get; set; }
        public string SortID { get; set; }
        public string FlagFile { get; set; }
        public string Culture { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public System.DateTime DateTimeModified { get; set; }
    }
}
