//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asis_tablelog
    {
        public int IDAsisTableLog { get; set; }
        public int IDAsisTableList { get; set; }
        public int RecordID { get; set; }
        public int IDUser { get; set; }
        public int IDAttRecordOperation { get; set; }
        public System.DateTime DateOperation { get; set; }
        public string Logchange { get; set; }
    }
}
