//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asis_translate
    {
        public int IDAsisTranslate { get; set; }
        public string WordsNL { get; set; }
        public string WordsEN { get; set; }
        public Nullable<int> IsStandard { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public string DateCreated { get; set; }
        public string DateModified { get; set; }
    }
}
