//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asis_tablelist
    {
        public int IDAsisTableList { get; set; }
        public Nullable<int> IDAsisModule { get; set; }
        public string TableName { get; set; }
        public string SortID { get; set; }
        public string HasHistory { get; set; }
        public string IsMultiLingual { get; set; }
        public string DescriptionNL { get; set; }
        public string DescriptionEN { get; set; }
        public string IDUserCreated { get; set; }
        public string IDUserModified { get; set; }
        public string DateCreated { get; set; }
        public string DateModified { get; set; }
    }
}
