//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSupportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_list
    {
        public int IDUser { get; set; }
        public string IDRelPerson { get; set; }
        public Nullable<int> IDUserGroup { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string IPAddressLocal { get; set; }
        public string IPAddressPubic { get; set; }
        public string MachineName { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public Nullable<int> IDUserCreated { get; set; }
        public Nullable<int> IDUserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
